SECURITY.md
Removing "governed by unified"
=> INTERNAL: Update SECURITY.md

README.md
=> INTERNAL: Update readme

.github/dependabot.yml, .github/workflows/dotnet-pullrequest-ubuntu.yml, .github/workflows/dotnet-pullrequest-windows.yml
=> INTERNAL: Add CI Builds for windows and ubuntu

.github/workflows/dotnet-pullrequest-windows.yml
=> INTERNAL: Try adding dotnet version

.github/workflows/dotnet-pullrequest-windows.yml
=> INTERNAL: Remove version input

.github/workflows/dotnet-pullrequest-windows.yml
=> Update version to be correct

.github/workflows/dotnet-pullrequest-windows.yml
=> Update to Release configuration for tests

.github/workflows/dotnet-pullrequest-windows.yml
=> Look for TestResults everywhere

.github/workflows/dotnet-pullrequest-windows.yml
=> Try different glob pattern

.github/workflows/dotnet-pullrequest-windows.yml
=> change to trx files

.github/workflows/dotnet-pullrequest-ubuntu.yml, .github/workflows/dotnet-pullrequest-windows.yml, .github/workflows/dotnet-release-publish-windows.yml
=> INTERNAL: Convert builds back to xml files

.github/workflows/dotnet-release-publish-ubuntu.yml, .github/workflows/dotnet-release-publish-windows.yml
=> INTERNAL: Update release creation scripts

.github/workflows/dotnet-release-publish-windows.yml
=> Publish nupkg for temp usage

.github/workflows/dotnet-release-publish-windows.yml
=> Fix syntax error

.github/workflows/dotnet-release-publish-windows.yml
=> INTERNAL: Dont add Nuget source when publishing with windows

.github/workflows/dotnet-pullrequest-windows.yml
=> INTERNAL: Add nuget caching

.github/workflows/dotnet-release-publish-windows.yml
=> INTERNAL: Use Cache in release flow, fix GH source name

.github/workflows/dotnet-release-publish-and-package-windows.yml, .github/workflows/dotnet-release-publish-windows.yml
=> Add release publishing for web/function apps

.github/workflows/dotnet-pullrequest-windows.yml, .github/workflows/dotnet-release-publish-windows.yml
=> Update cache settings

.github/workflows/dotnet-pullrequest-windows.yml
=> INTERNAL: Fix Typo

.github/workflows/create-octo-release-and-uploadpackage.yml, .github/workflows/create-octo-release.yml
=> INTERNAL: Add base workflows for creating releases in Octo

.github/workflows/create-octo-release.yml
=> Move env up to workflow
